### ISSUE TITLE
Testing roadmap

### ISSUE THREAD

**Issue by abulte** [swalladge/snsrv#7]
Before diving into some major refactoring, I would like to make sure that all current features are tested. Maybe we can use this issue as a tracker of what is tested and what needs to be tested?

- [x] web register
- [x] web login
- [x] web logout
- [x] web index
- [x] API create note
- [x] API login
- [x] API authorization (protected page)
- [x] API list notes
- [x] API get notes detail (no version)
- [ ] API get notes detail (with version)
- [x] API update note
- [x] API delete note after moving to trash
- [ ] tags
- [ ] ...

**Comment by swalladge** [comment]
I'm afraid the tests will have to be modified to work with tornado now... I don't really have any experience with setting up unit tests (and can't find info on using tornado with testing). I'll look into it soon though.

**Comment by abulte** [comment]
Cool! Let me know if you need something, I do not have a lot of time on my hand theses days though.
